import { StyleSheet } from 'react-native';
import { colors, typography, radius, spacing } from '../theme';

const fm = StyleSheet.create({
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: colors.gray100 },
  closeBtn: { width: 28 },
  title: { flex: 1, textAlign: 'center', fontSize: typography.lg, fontFamily: 'Poppins-Medium', color: colors.gray900 },
  body: { flex: 1, flexDirection: 'row' },
  sidebar: { width: '32%', backgroundColor: '#F9FAFB', borderRightWidth: 1, borderRightColor: colors.gray100 },
  tab: { paddingVertical: 16, paddingHorizontal: 12, borderLeftWidth: 4, borderLeftColor: 'transparent', borderBottomWidth: 1, borderBottomColor: colors.gray100 },
  tabActive: { backgroundColor: '#fff', borderLeftColor: colors.blue },
  tabText: { fontSize: typography.sm, color: colors.gray700, fontFamily: 'Poppins-Regular' },
  tabTextActive: { color: colors.blue, fontFamily: 'Poppins-Medium' },
  content: { flex: 1, backgroundColor: '#fff' },
  footer: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: colors.gray100 },
  clearBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 18 },
  clearText: { fontSize: typography.sm, fontFamily: 'Poppins-Medium', color: colors.gray500, letterSpacing: 0.5 },
  applyBtn: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 18, backgroundColor: colors.gray200 },
  applyBtnActive: { backgroundColor: colors.blue },
  applyText: { fontSize: typography.sm, fontFamily: 'Poppins-Medium', color: colors.gray500, letterSpacing: 0.5 },
  applyTextActive: { color: '#fff' },
});


const s = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F3F4F6' },
  headerBg: { backgroundColor: '#fff' },
  header: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing[4], paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.gray100 },
  backBtn: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center', marginRight: 4 },
  headerTitle: { fontSize: typography.md, fontFamily: 'Poppins-Medium', color: colors.gray900 },
  headerSub: { fontSize: typography.xs, color: colors.gray400, marginTop: 1, fontFamily: 'Poppins-Regular' },
  headerIconBtn: { width: 36, height: 36, alignItems: 'center', justifyContent: 'center' },
  pdfIconBtn: { width: 36, height: 36, borderRadius: radius.md, borderWidth: 1.5, borderColor: colors.blue, alignItems: 'center', justifyContent: 'center' },
  pdfIconText: { fontSize: 10, fontFamily: 'Poppins-Medium', color: colors.blue, letterSpacing: 0.5 },
  searchRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: spacing[4], paddingVertical: 10 },
  searchInput: { flex: 1, fontSize: typography.base, color: colors.gray900, fontFamily: 'Poppins-Regular' },
  filterScroll: { backgroundColor: '#F3F4F6' },
  filterRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: spacing[4], paddingVertical: 10 },
  filterIconBtn: { paddingHorizontal: 16, paddingVertical: 7, borderRadius: radius.full, borderWidth: 1.5, borderColor: colors.gray200, alignItems: 'center', justifyContent: 'center', backgroundColor: '#fff' },
  filterIconBtnActive: { borderColor: colors.blue, backgroundColor: colors.blueLight },
  filterChip: { flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: 12, paddingVertical: 7, borderRadius: radius.full, borderWidth: 1.5, borderColor: colors.gray200, backgroundColor: '#fff' },
  filterChipActive: { borderColor: colors.blue, backgroundColor: colors.blueLight },
  filterChipText: { fontSize: typography.sm, color: colors.gray600, fontFamily: 'Poppins-Regular' },
  filterChipTextActive: { color: colors.blue, fontFamily: 'Poppins-Medium' },
  balCard: { marginHorizontal: spacing[4], marginTop: spacing[2], backgroundColor: '#fff', borderRadius: radius.md, overflow: 'hidden' },
  balCardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: spacing[4], borderBottomWidth: 1, borderBottomColor: colors.gray100 },
  balLabel: { fontSize: typography.md, fontFamily: 'Poppins-Medium', color: colors.gray900 },
  balAmount: { fontSize: typography.md, fontFamily: 'Poppins-Medium', color: colors.gray900 },
  balCardRow: { padding: spacing[4], paddingBottom: spacing[4] },
  balCardItem: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing[2] },
  balSmLabel: { fontSize: typography.sm, color: colors.gray900, fontFamily: 'Poppins-Medium' },
  balSmAmount: { fontSize: typography.sm, fontFamily: 'Poppins-Medium' },
  viewReportsBtn: { paddingVertical: spacing[3], borderTopWidth: 1, borderTopColor: colors.gray100, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 4 },
  viewReportsText: { fontSize: typography.sm, fontFamily: 'Poppins-Medium', color: colors.blue, letterSpacing: 0.5 },
  countLabelWrap: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing[4], paddingVertical: 16 },
  countLine: { flex: 1, height: 1, backgroundColor: colors.gray200 },
  countLabel: { fontSize: 11, color: colors.gray500, marginHorizontal: 8, fontFamily: 'Poppins-Regular' },
  list: { paddingBottom: 100 },
  dateHeader: { fontSize: typography.xs, fontFamily: 'Poppins-Medium', color: colors.gray500, paddingHorizontal: spacing[4], paddingVertical: 8 },
  txnRow: { backgroundColor: '#fff', padding: spacing[4], marginBottom: spacing[2] },
  txnTop: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 4 },
  paymentBadge: { backgroundColor: '#E0F2FE', paddingHorizontal: 8, paddingVertical: 2, borderRadius: radius.sm },
  paymentBadgeText: { fontSize: typography.xs, color: colors.blue, fontFamily: 'Poppins-Medium' },
  txnParty: { fontSize: typography.md, fontFamily: 'Poppins-Medium', color: colors.gray900 },
  txnAmount: { fontSize: typography.md, fontFamily: 'Poppins-Medium' },
  txnBalance: { fontSize: typography.xs, color: colors.gray500, marginTop: 2, fontFamily: 'Poppins-Regular' },
  txnRemarks: { fontSize: typography.sm, color: colors.gray500, marginTop: 4, fontFamily: 'Poppins-Regular' },
  attachmentRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
  attachmentText: { fontSize: typography.xs, color: colors.gray400, fontFamily: 'Poppins-Regular' },
  txnBottom: { marginTop: 8 },
  txnEntry: { fontSize: 11, color: colors.gray500, fontFamily: 'Poppins-Regular' },
  emptyState: { paddingTop: 16, paddingBottom: 40, alignItems: 'center' },
  emptyContent: { alignItems: 'center', marginTop: 20 },
  emptyTitle: { fontSize: typography.xl, fontFamily: 'Poppins-Medium', color: colors.gray700 },
  emptyLabels: { flexDirection: 'row', gap: 32 },
  emptyLabel: { fontSize: typography.base, fontFamily: 'Poppins-Medium' },
  privacyBadge: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 14, marginHorizontal: spacing[4], backgroundColor: '#fff', borderRadius: radius.md, marginBottom: 8 },
  privacyText: { fontSize: typography.xs, color: colors.gray600, fontFamily: 'Poppins-Regular' },
  center: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingTop: 40 },
  bottomBar: { flexDirection: 'row', backgroundColor: '#F3F4F6', paddingHorizontal: spacing[4], paddingVertical: 12, gap: spacing[4] },
  bottomBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 14, borderRadius: radius.md },
  bottomBtnText: { color: '#fff', fontFamily: 'Poppins-Medium', fontSize: typography.md, letterSpacing: 0.5 },
  toast: { position: 'absolute', bottom: 80, left: spacing[4], right: spacing[4], backgroundColor: '#1F2937', borderRadius: radius.xl, flexDirection: 'row', alignItems: 'center', gap: 10, paddingHorizontal: 16, paddingVertical: 12 },
  toastText: { flex: 1, color: '#fff', fontFamily: 'Poppins-Medium', fontSize: typography.sm },
  menuOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.1)' },
  menuContainer: { position: 'absolute', top: 50, right: 16, backgroundColor: '#fff', borderRadius: radius.md, elevation: 5, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.15, shadowRadius: 4, minWidth: 220, paddingVertical: 8, borderWidth: 1, borderColor: colors.gray100 },
  menuItem: { flexDirection: 'row', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 16, gap: 14 },
  menuItemText: { fontSize: typography.sm, color: colors.gray800, fontFamily: 'Poppins-Regular' }
});

const b = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  sheet: { backgroundColor: '#fff', borderTopLeftRadius: 20, borderTopRightRadius: 20, maxHeight: '75%' },
  header: { flexDirection: 'row', alignItems: 'center', gap: 14, paddingHorizontal: spacing[4], paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: colors.gray100 },
  closeBtn: { width: 28 },
  title: { fontSize: typography.xl, fontFamily: 'Poppins-Medium', color: colors.gray900 },
  scrollArea: { flexGrow: 0 },
  optRow: { flexDirection: 'row', alignItems: 'center', gap: 18, paddingVertical: 16, paddingHorizontal: spacing[4] },
  optRowActive: { backgroundColor: '#EEEEFF' },
  radio: { width: 24, height: 24, borderRadius: 12, borderWidth: 2, borderColor: colors.gray300, alignItems: 'center', justifyContent: 'center' },
  radioActive: { borderColor: colors.blue },
  radioDot: { width: 11, height: 11, borderRadius: 6, backgroundColor: colors.blue },
  optLabel: { fontSize: typography.md, color: colors.gray700, fontFamily: 'Poppins-Regular' },
  optLabelActive: { color: colors.gray900, fontFamily: 'Poppins-Medium' },
  searchBox: { flexDirection: 'row', alignItems: 'center', gap: 10, marginHorizontal: spacing[4], marginTop: 12, marginBottom: 4, borderWidth: 1.5, borderColor: colors.gray200, borderRadius: radius.lg, paddingHorizontal: 12, paddingVertical: 10 },
  searchInput: { flex: 1, fontSize: typography.base, color: colors.gray900, fontFamily: 'Poppins-Regular' },
  sectionLabel: { fontSize: typography.sm, color: colors.gray400, paddingHorizontal: spacing[4], paddingTop: 14, paddingBottom: 6, fontFamily: 'Poppins-Regular' },
  checkRow: { flexDirection: 'row', alignItems: 'center', gap: 18, paddingVertical: 16, paddingHorizontal: spacing[4] },
  checkbox: { width: 22, height: 22, borderRadius: 4, borderWidth: 2, borderColor: colors.gray300, alignItems: 'center', justifyContent: 'center' },
  checkboxActive: { backgroundColor: colors.blue, borderColor: colors.blue },
  checkLabel: { fontSize: typography.md, color: colors.gray800, fontFamily: 'Poppins-Regular' },
  divider: { height: 1, backgroundColor: colors.gray100, marginLeft: spacing[4] + 22 + 18 },
  emptyText: { textAlign: 'center', color: colors.gray400, paddingVertical: 20, fontSize: typography.base, fontFamily: 'Poppins-Regular' },
  footer: { flexDirection: 'row', borderTopWidth: 1, borderTopColor: colors.gray100 },
  clearBtn: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, paddingVertical: 18 },
  clearText: { fontSize: typography.sm, fontFamily: 'Poppins-Medium', color: colors.gray400, letterSpacing: 0.5 },
  applyBtn: { flex: 1.5, alignItems: 'center', justifyContent: 'center', paddingVertical: 18, backgroundColor: colors.gray200 },
  applyBtnActive: { backgroundColor: colors.blue },
  applyText: { fontSize: typography.sm, fontFamily: 'Poppins-Medium', color: colors.gray500, letterSpacing: 0.5 },
  applyTextActive: { color: '#fff' }
});

export { fm, s, b };
